### ISSUE TITLE
Make GitHub's language statistics see *.conf as nginx configuration files

### ISSUE THREAD

**Issue by virgilwashere** [dvershinin/NginxConfig#1]
If you're interested, you can add a `.gitattributes` file to the repo to classify nginx config files correctly.

<details>
<summary>.gitattributes</summary>

```gitconfig
# Auto detect text files and perform LF normalization
# http://davidlaing.com/2012/09/19/customise-your-gitattributes-to-become-a-git-ninja/
*	text=auto	eol=lf

# Make GitHub's language statistics treat the `*.conf` files as
# Nginx configuration files
# https://github.com/github/linguist/blob/master/README.md

**/nginx/**/*.conf		text    eol=lf    linguist-language=Nginx
**/nginx/**/*.conf.off	text	eol=lf    linguist-language=Nginx
**/nginx/**/*_params	text    eol=lf    linguist-language=Nginx
*.conf.nginx			text    eol=lf    linguist-language=Nginx
#**/nginx/{sites-available,sites-templates,conf.d,global}/*.conf text eol=lf linguist-language=Nginx

#*.conf		text	eol=lf
```

</details>

**Comment by dvershinin** [comment]
It's quite sweet. However, I did not see how to make this work using your config.
Searched a few reference repos that include `linguist-language=Nginx`.

It's interesting for example with [this one](https://github.com/vsund/nginx-config), the Nginx is being reported in stats bar, but when you click on it, this only includes `nginx.conf` (which was not listed in `.gitattributes`).

So I guess, GitHub automatically detects NGINX config from filename `nginx.conf`, but `.gitattributes` did not apply for some reason.

Maybe because of [Detectable](https://github.com/github/linguist/blob/master/README.md#detectable)... Which does not explain why `nginx.conf` was marked properly in the reference repo, even it didn't have `linguist-detectable=true`...

**Comment by dvershinin** [comment]
So after adding `linguist-detectable=true` - this updated the stats bar to include NGINX, but only `nginx.conf` is included in "search results" (which I guess is GitHub limitation/bug). 

Thanks :)
